#!/bin/bash

#script used to transform instance file into dat file
#used as input of glpsol steiner tree model.

instance_dir=$1

#application used to convert mpp instance into data instance for glpsol
datagen="build/datagen"

#filtering the mpp instances
files=`find $instance_dir -name "*.brite"`

#generating the data instances for glpsol
for i in $files
do
	$datagen `readlink -f $i` 0
done

#getting the files generated by datagen
files=`find $instance_dir -name "*.dat"`

#create directory for store the *.dat files
mkdir -p $instance_dir/mpp_dat_files

#moving the files to mpp_dat_files
for i in $files
do
	#getting the file name with no directory name
	f=`basename $i`

	#moving
	mv `readlink -f $i` $instance_dir/mpp_dat_files/$f
done

